package frc.robot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import frc.robot.RobotMap;

public class IO
{  
    // This file contains all gamepad button inputs, axis inputs, and dpad angles.
    // The buttons are to be used in OI, and the axis and dpad inputs are to be used in commands.
    // Do not edit this file, unless the integer values given are wrong.
    
    public final Joystick leftJoy = new Joystick(RobotMap.leftJoyPort);
    public final Joystick rightJoy = new Joystick(RobotMap.rightJoyPort);
    public final Joystick mechJoy = new Joystick(RobotMap.mechJoyPort);
  
    public JoystickButton leftTrigger = new JoystickButton(leftJoy, 1),
        leftButton2 = new JoystickButton(leftJoy, 2),
        leftButton3 = new JoystickButton(leftJoy, 3),
        leftButton4 = new JoystickButton(leftJoy, 4),
        leftButton5 = new JoystickButton(leftJoy, 5),
        leftButton6 = new JoystickButton(leftJoy, 6),
        leftButton7 = new JoystickButton(leftJoy, 7),
        leftButton8 = new JoystickButton(leftJoy, 8),
        leftButton9 = new JoystickButton(leftJoy, 9),
        leftButton10 = new JoystickButton(leftJoy, 10),
        leftButton11 = new JoystickButton(leftJoy, 11),
        leftButton12 = new JoystickButton(leftJoy, 12);

    public double getLeftJoyX()
    {
        return leftJoy.getRawAxis(0);
    }

    public double getLeftJoyY()
    {
        return leftJoy.getRawAxis(1);
    }

    public double getLeftJoyThrottle()
    {
        return leftJoy.getRawAxis(2);
    }

    public JoystickButton rightTrigger = new JoystickButton(rightJoy, 1),
        rightButton2 = new JoystickButton(rightJoy, 2),
        rightButton3 = new JoystickButton(rightJoy, 3),
        rightButton4 = new JoystickButton(rightJoy, 4),
        rightButton5 = new JoystickButton(rightJoy, 5),
        rightButton6 = new JoystickButton(rightJoy, 6),
        rightButton7 = new JoystickButton(rightJoy, 7),
        rightButton8 = new JoystickButton(rightJoy, 8),
        rightButton9 = new JoystickButton(rightJoy, 9),
        rightButton10 = new JoystickButton(rightJoy, 10),
        rightButton11 = new JoystickButton(rightJoy, 11),
        rightButton12 = new JoystickButton(rightJoy, 12);

    public double getRightJoyX()
    {
        return rightJoy.getRawAxis(0);
    }

    public double getRightJoyY()
    {
        return rightJoy.getRawAxis(1);
    }

    public double getRightJoyThrottle()
    {
        return rightJoy.getRawAxis(2);
    }

    public JoystickButton mechTrigger = new JoystickButton(mechJoy, 1),
        mechButton2 = new JoystickButton(mechJoy, 2),
        mechButton3 = new JoystickButton(mechJoy, 3),
        mechButton4 = new JoystickButton(mechJoy, 4),
        mechButton5 = new JoystickButton(mechJoy, 5),
        mechButton6 = new JoystickButton(mechJoy, 6),
        mechButton7 = new JoystickButton(mechJoy, 7),
        mechButton8 = new JoystickButton(mechJoy, 8),
        mechButton9 = new JoystickButton(mechJoy, 9),
        mechButton10 = new JoystickButton(mechJoy, 10),
        mechButton11 = new JoystickButton(mechJoy, 11),
        mechButton12 = new JoystickButton(mechJoy, 12);

    public double getMechJoyX()
    {
        return mechJoy.getRawAxis(0);
    }

    public double getMechJoyY()
    {
        return mechJoy.getRawAxis(1);
    }

    public double getMechJoyThrottle()
    {
        return mechJoy.getRawAxis(2);
    }
}